name: Check for updates

permissions:
  contents: write
  pull-requests: write
  issues: write

on:
  schedule: # for scheduling to work this file must be in the default branch
    - cron: "0 * * * *" # run every hour
  workflow_dispatch: # can be manually dispatched under GitHub's "Actions" tab

jobs:
  update-sources:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch: [master]

    steps:
      - name: Get latest tag from noriskclient-launcher
        id: get-tag
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/NoRiskClient/noriskclient-launcher/releases/latest | jq -r '.tag_name')
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Checkout the noriskclient-launcher repository
        uses: actions/checkout@v4
        with:
          repository: NoRiskClient/noriskclient-launcher
          path: noriskclient-launcher
          ref: ${{ steps.get-tag.outputs.latest_tag }}

      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          path: flathub

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('flatpak-builder-tools/cargo/requirements.txt', 'flatpak-builder-tools/node/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install pip dependencies for cargo generator
        run: pip install tomlkit aiohttp

      - name: Checkout flatpak-builder-tools
        uses: actions/checkout@v4
        with:
          repository: flatpak/flatpak-builder-tools
          path: flatpak-builder-tools

      - name: Generate cargo-sources.json
        run: |
          if [ -f noriskclient-launcher/src-tauri/Cargo.lock ]; then
            python3 flatpak-builder-tools/cargo/flatpak-cargo-generator.py noriskclient-launcher/src-tauri/Cargo.lock -o flathub/cargo-sources.json
          fi

      - name: Install flatpak-node-generator
        run: pipx install git+https://github.com/flatpak/flatpak-builder-tools.git#subdirectory=node

      - name: Generate node-sources.json (Yarn)
        run: |
          if [ -f noriskclient-launcher/yarn.lock ]; then
            flatpak-node-generator yarn noriskclient-launcher/yarn.lock -o flathub/node-sources.json
          fi

      - name: Commit changes
        run: |
          cd flathub
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Get latest version info for better commit messages
          LAUNCHER_VERSION=$(cd ../noriskclient-launcher && git describe --tags --always)

          FILES_TO_COMMIT=""
          if [ -f cargo-sources.json ]; then
            FILES_TO_COMMIT="$FILES_TO_COMMIT cargo-sources.json"
          fi
          if [ -f node-sources.json ]; then
            FILES_TO_COMMIT="$FILES_TO_COMMIT node-sources.json"
          fi

          if [ -n "$FILES_TO_COMMIT" ] && [[ $(git status --porcelain $FILES_TO_COMMIT) ]]; then
            git add -- $FILES_TO_COMMIT
            git commit -m "chore: update flatpak dependency manifests for launcher ${LAUNCHER_VERSION}"
            git push origin HEAD:${GITHUB_REF#refs/heads/}
          else
            echo "No changes to commit."
          fi
  flatpak-external-data-checker:
    runs-on: ubuntu-latest

    needs: update-sources

    strategy:
      matrix:
        branch: [master] # list all branches to check

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
        env:
          GIT_AUTHOR_NAME: Flatpak External Data Checker
          GIT_COMMITTER_NAME: Flatpak External Data Checker
          # email sets "github-actions[bot]" as commit author, see https://github.community/t/github-actions-bot-email-address/17204/6
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --update --never-fork gg.norisk.NoRiskClientLauncherV3.yml
