name: Check for updates

permissions:
  contents: write
  pull-requests: write
  issues: write

on:
  schedule: # for scheduling to work this file must be in the default branch
    - cron: "0 * * * *" # run every hour
  workflow_dispatch: # can be manually dispatched under GitHub's "Actions" tab

jobs:
  update-sources:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch: [master, beta]

    steps:
      - name: Get latest tag from noriskclient-launcher
        id: get-tag
        run: |
          # For master branch use the latest stable release (GitHub releases/latest is non-prerelease)
          if [ "${{ matrix.branch }}" = "master" ]; then
            LATEST_TAG=$(curl -s https://api.github.com/repos/NoRiskClient/noriskclient-launcher/releases/latest | jq -r '.tag_name')
          else
            # For beta branch pick the most recent prerelease (GitHub releases API returns newest first)
            LATEST_TAG=$(curl -s https://api.github.com/repos/NoRiskClient/noriskclient-launcher/releases | jq -r '.[] | select(.prerelease==true) | .tag_name' | head -n1)
          fi

          if [ -z "$LATEST_TAG" ] || [ "$LATEST_TAG" = "null" ]; then
            echo "No suitable tag found for branch '${{ matrix.branch }}'. Exiting without changes."
            # exit 0 so the job succeeds but nothing is attempted when no release/prerelease exists
            exit 0
          fi

          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Checkout the noriskclient-launcher repository
        uses: actions/checkout@v4
        with:
          repository: NoRiskClient/noriskclient-launcher
          path: noriskclient-launcher
          ref: ${{ steps.get-tag.outputs.latest_tag }}

      - name: Checkout this repository (flathub branch)
        uses: actions/checkout@v4
        with:
          path: flathub
          ref: ${{ matrix.branch }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('flatpak-builder-tools/cargo/requirements.txt', 'flatpak-builder-tools/node/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install pip dependencies for cargo generator
        run: pip install tomlkit aiohttp

      - name: Checkout flatpak-builder-tools
        uses: actions/checkout@v4
        with:
          repository: flatpak/flatpak-builder-tools
          path: flatpak-builder-tools

      - name: Generate cargo-sources.json
        run: |
          if [ -f noriskclient-launcher/src-tauri/Cargo.lock ]; then
            python3 flatpak-builder-tools/cargo/flatpak-cargo-generator.py noriskclient-launcher/src-tauri/Cargo.lock -o flathub/cargo-sources.json
          fi

      - name: Install flatpak-node-generator
        run: pipx install git+https://github.com/flatpak/flatpak-builder-tools.git#subdirectory=node

      - name: Generate node-sources.json (Yarn)
        run: |
          if [ -f noriskclient-launcher/yarn.lock ]; then
            flatpak-node-generator yarn noriskclient-launcher/yarn.lock -o flathub/node-sources.json
          fi

      - name: Commit generated dependency manifests (local commit only)
        run: |
          cd flathub
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Get latest version info for better commit messages
          LAUNCHER_VERSION=$(cd ../noriskclient-launcher && git describe --tags --always)

          FILES_TO_COMMIT=""
          if [ -f cargo-sources.json ]; then
            FILES_TO_COMMIT="$FILES_TO_COMMIT cargo-sources.json"
          fi
          if [ -f node-sources.json ]; then
            FILES_TO_COMMIT="$FILES_TO_COMMIT node-sources.json"
          fi

          if [ -n "$FILES_TO_COMMIT" ] && [[ $(git status --porcelain $FILES_TO_COMMIT) ]]; then
            git add -- $FILES_TO_COMMIT
            git commit -m "chore: update flatpak dependency manifests for launcher ${LAUNCHER_VERSION} (branch: ${{ matrix.branch }})"
            echo "Committed dependency manifest updates locally. These commits will be included in the update PR."
          else
            echo "No changes to commit."
          fi

      - name: Run flatpak external data checker (create/update PR branch including the local commits)
        uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
        env:
          GIT_AUTHOR_NAME: Flatpak External Data Checker
          GIT_COMMITTER_NAME: Flatpak External Data Checker
          # email sets "github-actions[bot]" as commit author, see https://github.community/t/github-actions-bot-email-address/17204/6
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Use --update so the checker will commit its changes, create the branch in-repo and open the PR.
          # Pass the manifest path relative to the repository root (the flathub manifests live under flathub/).
          args: --update --never-fork flathub/gg.norisk.NoRiskClientLauncherV3.yml
